from pathlib import Path

import polars as pl
from rdkit import Chem

from polaris_asap_poses.download import (
    get_df_test_for_comp,
    get_df_train_for_comp,
    load_comp,
)
from polaris_asap_poses.io import (
    DATA_DIR_GNINA_OUT,
    DATA_DIR_LIGAND_SDF,
    POLARIS_ASAP_POSES_HOME,
    read_sdf,
    write_sdf,
)
from polaris_asap_poses.logger import logger
from polaris_asap_poses.model import MERS, SARS
from polaris_asap_poses.util import print_info


##################################################
# Preprocessing - prep for gnina run
##################################################
def write_test_ligand_sdfs():
    """
    Write ligands from the test dataset to SDF, for use by gnina.
    """
    logger.info("Start.")
    comp = load_comp()
    df_test = get_df_test_for_comp(comp)
    for row in df_test.iter_rows(named=True):
        logger.info(
            f"Processing id {row['test_fake_id']}, protein {row['protein_label']}, CXSMILES {row['CXSMILES']}..."
        )

        match row["protein_label"]:
            case SARS.data_label:
                this_protein = SARS
            case MERS.data_label:
                this_protein = MERS
            case _:
                raise ValueError(
                    f"Invalid protein_label {row['protein_label']} for test_fake_id {row['test_fake_id']}"
                )

        ligand_sdf_path = (
            DATA_DIR_LIGAND_SDF
            / f"test_{row['test_fake_id']}_{this_protein.path_segment}.sdf"
        )
        docking_result_path = (
            DATA_DIR_GNINA_OUT
            / f"docked_test_{row['test_fake_id']}_{this_protein.path_segment}.sdf"
        )
        mol = Chem.MolFromSmiles(row["CXSMILES"])
        write_sdf(mol=mol, path=ligand_sdf_path)
    logger.info("Done.")


##################################################
# Postprocessing - after gnina results are ready
##################################################
def get_df_sdfs(sdf_dir: Path | str = DATA_DIR_GNINA_OUT) -> pl.DataFrame:
    """
    For a directory of sdfs generated by gnina, get a dataframe with each file's path, protein, ID, and train-or-testness
    """
    logger.info(f"Loading gnina output sdfs from {sdf_dir}...")
    sdf_dir = Path(sdf_dir)
    sdfs = sorted([i for i in sdf_dir.glob("*.sdf")])
    test_or_train = []
    ligand_ids = []
    protein_labels = []
    for i in sdfs:
        test_or_train.append(i.name.split("_")[1])
        ligand_ids.append(i.name.split("_")[2])
        protein_labels.append(i.name.split("_")[3][:-4])
    df_sdfs = pl.DataFrame(
        {
            "sdf": sdfs,
            "test_or_train": test_or_train,
            "ligand_id": ligand_ids,
            "protein_label": protein_labels,
        }
    )
    df_sdfs = df_sdfs.with_columns(
        [pl.col("ligand_id").cast(pl.Int32).alias("ligand_id")]
    )
    df_sdfs = df_sdfs.sort(by=["ligand_id"], descending=False)
    print_info(df_sdfs)
    return df_sdfs


def get_top_cnnscore_for_sdf(sdf_file: Path | str) -> Chem.Mol:
    """
    For an SDF generated by gnina, return the mol with the highest CNNscore
    """
    mols = read_sdf(sdf_file)
    best_mol = None
    best_score = -float("inf")
    for mol in mols:
        if mol is None:
            continue
        score = float(mol.GetProp("CNNscore"))
        logger.debug(score)
        if score > best_score:
            best_score = score
            best_mol = mol
    return best_mol


def get_mol_data_for_sdfs(df_sdfs: pl.DataFrame) -> pl.DataFrame:
    """
    Add the top-scoring mol from each SDF to its row in df_sdf.
    """
    logger.info(f"Updating df_sdfs with mol data...")
    print_info(df_sdfs)
    top_mols = []
    top_mol_minimized_affinities = []
    top_mol_cnn_scores = []
    top_mol_cnn_affinities = []
    top_mol_cnn_vses = []
    top_mol_cnn_affinity_variances = []
    for row in df_sdfs.iter_rows(named=True):
        logger.debug(f"Processing {row["ligand_id"]}...")
        top_mol = get_top_cnnscore_for_sdf(row["sdf"])
        top_mol_minimized_affinity = float(top_mol.GetProp("minimizedAffinity"))
        top_mol_cnn_score = float(top_mol.GetProp("CNNscore"))
        top_mol_cnn_affinity = float(top_mol.GetProp("CNNaffinity"))
        top_mol_cnn_vs = float(top_mol.GetProp("CNN_VS"))
        top_mol_cnn_affinity_variance = float(top_mol.GetProp("CNNaffinity_variance"))
        top_mols.append(top_mol)
        top_mol_minimized_affinities.append(top_mol_minimized_affinity)
        top_mol_cnn_scores.append(top_mol_cnn_score)
        top_mol_cnn_affinities.append(top_mol_cnn_affinity)
        top_mol_cnn_vses.append(top_mol_cnn_vs)
        top_mol_cnn_affinity_variances.append(top_mol_cnn_affinity_variance)
    df_sdfs = df_sdfs.with_columns(
        [
            pl.Series(name="best_mol", values=top_mols),
            pl.Series(name="cnn_score", values=top_mol_cnn_scores),
            pl.Series(name="minimized_affinity", values=top_mol_minimized_affinities),
            pl.Series(name="cnn_affinity", values=top_mol_cnn_affinities),
            pl.Series(name="cnn_vs", values=top_mol_cnn_vses),
            pl.Series(
                name="cnn_affinity_variance", values=top_mol_cnn_affinity_variances
            ),
        ]
    )
    logger.info("Done.  Updated dataframe:")
    print_info(df_sdfs)
    return df_sdfs


def postprocess_gnina_out(sdf_dir: Path | str = DATA_DIR_GNINA_OUT) -> pl.DataFrame:
    logger.info(f"Postprocessing gnina output data from {sdf_dir}...")
    df_sdfs = get_df_sdfs(sdf_dir=sdf_dir)
    df_sdfs = get_mol_data_for_sdfs(df_sdfs=df_sdfs)
    logger.info("Done.")
    return df_sdfs

def add_rmsd_col(df_both: pl.DataFrame) -> pl.DataFrame:
    """
    Add column with rmsd between each ligand's best pose for exhaustiveness=16 vs exhaustiveness=64.
    """
    from spyrmsd.molecule import Molecule
    from spyrmsd.rmsd import rmsdwrapper
    rmsds = []
    for row in df_both.iter_rows(named=True):
        mol_16 = Molecule.from_rdkit(row["best_mol_16"])
        mol_64 = Molecule.from_rdkit(row["best_mol_64"])
        rmsd = rmsdwrapper(mol_16, mol_64)[0] # should be just one element here
        rmsds.append(rmsd)
    df_both = df_both.with_columns([pl.Series(name="rmsd", values=rmsds)])
    return df_both

def compare_16_and_64() -> pl.DataFrame:
    """
    I've got gnina results for the test dataset run with either `--exhaustiveness 16` or `--exhaustiveness 64`
    Let's join 'em up and see what we can see.
    """
    DATA_DIR_GNINA_OUT_16 = (
        Path(POLARIS_ASAP_POSES_HOME) / "data/gnina-out-1-exhaustiveness-16"
    )
    DATA_DIR_GNINA_OUT_64 = (
        Path(POLARIS_ASAP_POSES_HOME) / "data/gnina-out-2-exhaustiveness-64"
    )
    df_sdfs_16 = postprocess_gnina_out(DATA_DIR_GNINA_OUT_16)
    df_sdfs_64 = postprocess_gnina_out(DATA_DIR_GNINA_OUT_64)
    df_sdfs_16 = df_sdfs_16.rename(
        lambda column_name: (
            column_name + "_16"
            if column_name not in ["test_or_train", "ligand_id", "protein_label"]
            else column_name
        )
    )
    df_sdfs_64 = df_sdfs_64.rename(
        lambda column_name: (
            column_name + "_64"
            if column_name not in ["test_or_train", "ligand_id", "protein_label"]
            else column_name
        )
    )
    df_both = df_sdfs_16.join(
        df_sdfs_64, on=["test_or_train", "ligand_id", "protein_label"], how="inner"
    )
    df_both = add_rmsd_col(df_both=df_both)
    df_both = df_both.select(
        [
            "test_or_train",
            "ligand_id",
            "protein_label",
            "rmsd",
            "cnn_score_16",
            "cnn_score_64",
            "minimized_affinity_16",
            "minimized_affinity_64",
            "cnn_affinity_16",
            "cnn_affinity_64",
            "cnn_vs_16",
            "cnn_vs_64",
            "cnn_affinity_variance_16",
            "cnn_affinity_variance_64",
            "best_mol_16",
            "best_mol_64",
            "sdf_16",
            "sdf_64",
        ]
    )
    return df_both
