from polaris_asap_poses.download import load_comp, get_df_train_for_comp, get_df_test_for_comp
from polaris_asap_poses.io import DATA_DIR_LIGAND_SDF, write_sdf, DATA_DIR_GNINA_OUT, read_sdf
from polaris_asap_poses.model import SARS, MERS
from polaris_asap_poses.logger import logger
from pathlib import Path
from rdkit import Chem
import polars as pl

def get_df_sdfs(sdf_dir: Path | str = DATA_DIR_GNINA_OUT) -> pl.DataFrame:
    """
    For a directory of sdfs generated by gnina, get a dataframe with each file's path, protein, ID, and train-or-testness
    """
    sdf_dir = Path(sdf_dir)
    sdfs = sorted([i for i in sdf_dir.glob("*.sdf")])
    test_or_train = []
    ligand_ids = []
    protein_labels = []
    for i in sdfs:
        test_or_train.append(i.name.split("_")[1])
        ligand_ids.append(i.name.split("_")[2])
        protein_labels.append(i.name.split("_")[3][:-4])
    df_sdfs = pl.DataFrame({"sdf": sdfs, "test_or_train": test_or_train, "ligand_id": ligand_ids, "protein_label": protein_labels})
    df_sdfs = df_sdfs.with_columns([pl.col("ligand_id").cast(pl.Int32).alias("ligand_id")])
    df_sdfs = df_sdfs.sort(by=["ligand_id"], descending=False)
    return df_sdfs

def get_top_cnnscore_for_sdf(sdf_file: Path |str) -> Chem.Mol:
    """
    For an SDF generated by gnina, return the mol with the highest CNNscore
    """
    mols = read_sdf(sdf_file)
    best_mol = None
    best_score = -float("inf")
    for mol in mols:
        if mol is None:
            continue
        score = float(mol.GetProp("CNNscore"))
        logger.debug(score)
        if score > best_score:
            best_score = score
            best_mol = mol
    return best_mol

def write_test_ligand_sdfs():
    logger.info("Start.")
    comp = load_comp()
    df_test = get_df_test_for_comp(comp)
    for row in df_test.iter_rows(named=True):
        logger.info(f"Processing id {row['test_fake_id']}, protein {row['protein_label']}, CXSMILES {row['CXSMILES']}...")

        match row["protein_label"]:
            case SARS.data_label:
                this_protein = SARS
            case MERS.data_label:
                this_protein = MERS
            case _:
                raise ValueError(f"Invalid protein_label {row['protein_label']} for test_fake_id {row['test_fake_id']}")

        ligand_sdf_path = DATA_DIR_LIGAND_SDF / f"test_{row['test_fake_id']}_{this_protein.path_segment}.sdf"
        docking_result_path = DATA_DIR_GNINA_OUT / f"docked_test_{row['test_fake_id']}_{this_protein.path_segment}.sdf"
        mol = Chem.MolFromSmiles(row["CXSMILES"])
        write_sdf(mol=mol, path=ligand_sdf_path)
    logger.info("Done.")

if __name__ == "__main__":
    write_test_ligand_sdfs()
